plugins {
	id 'java'
}

group = 'synapticloop'
archivesBaseName = 'backblaze-b2-java-api'
version = '2.2.1'

sourceCompatibility = 1.7
targetCompatibility = 1.7

repositories {
	mavenLocal()
	mavenCentral()
	jcenter()
}

dependencies {
	compile 'org.apache.httpcomponents:httpclient:4.5.2'
	compile 'commons-io:commons-io:2.5'
	compile 'org.json:json:20160810'
	compile 'org.slf4j:slf4j-api:1.7.13'
	
	testCompile 'junit:junit:4.12'
	testCompile 'org.apache.logging.log4j:log4j-slf4j-impl:2.7'
	testCompile 'org.apache.logging.log4j:log4j-core:2.7'
}