name: Integration Tests

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
      - name: Build with Maven
        env:
          B2_ACCOUNT_ID: ${{ secrets.B2_ACCOUNT_ID }}
          B2_APPLICATION_KEY: ${{ secrets.B2_APPLICATION_KEY }}
        run: mvn --no-transfer-progress --batch-mode test
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1.9.0
